export { ProductMainSection } from "./product-main-section"
export { SellerInfo } from "./seller-info"
export { ProductSpecifications } from "./product-specifications"
export { ReviewsSection } from "./reviews-section"
export { RelatedProducts } from "./related-products"
